"""empty message

Revision ID: ad731b386229
Revises: 
Create Date: 2019-10-27 19:27:29.047067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad731b386229'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bukti_bayar', 'historybelanja', ['id_history_belanja'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bukti_bayar', type_='foreignkey')
    # ### end Alembic commands ###
