"""empty message

Revision ID: fd0eadc846a4
Revises: ad731b386229
Create Date: 2019-11-01 15:45:37.824043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd0eadc846a4'
down_revision = 'ad731b386229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('foto_user', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'foto_user')
    # ### end Alembic commands ###
